### ISSUE TITLE
does not compile with ghc-8.4

### ISSUE THREAD

**Issue by 0x777** [tdammers/ginger#35]
```
   /tmp/stack26892/ginger-0.7.3.0/src/Text/Ginger/Html.hs:24:15: error:
        • No instance for (Semigroup Html)
            arising from the 'deriving' clause of a data type declaration
          Possible fix:
            use a standalone 'deriving instance' declaration,
              so you can specify the instance context yourself
        • When deriving the instance for (Monoid Html)
       |
    24 |     deriving (Monoid, Show, Eq, Ord)
       |               ^^^^^^
```

I fixed this at https://github.com/hasura/ginger. I can submit a PR if needed.

**Comment by tdammers** [comment]
Please do. I could easily do it myself, but since you've already got a
patch...

**Comment by tdammers** [comment]
Fixed in https://github.com/tdammers/ginger/pull/36.
