### ISSUE TITLE
fails to build with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [tdammers/ginger#82]
With Stackage Nightly and ghc-9.10.2:

```
       Building executable 'ginger' for ginger-0.10.5.2...                                                    12:58:25 [5955/954403]
       [1 of 2] Compiling Options 
       [2 of 2] Compiling Main
       /home/curators/work/unpack-dir/unpacked/ginger-0.10.5.2-3c5c7e74779496d7de83bb400b7136656af67e5ccce8547b49055424c541c136/cli/
GingerCLI.hs:84:37: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at cli/GingerCLI.hs:7:8-11
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘Text.show’,
                     imported from ‘Data.Text’ at cli/GingerCLI.hs:11:1-24.
          |
       84 |                 (hPutStrLn stderr . show)
          |                                     ^^^^
        
       /home/curators/work/unpack-dir/unpacked/ginger-0.10.5.2-3c5c7e74779496d7de83bb400b7136656af67e5ccce8547b49055424c541c136/cli/
GingerCLI.hs:87:59: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at cli/GingerCLI.hs:7:8-11
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘Text.show’,
                     imported from ‘Data.Text’ at cli/GingerCLI.hs:11:1-24.
          |
       87 |     runGingerT context tpl >>= either (hPutStrLn stderr . show) showOutput
          |                                                           ^^^^
        
       /home/curators/work/unpack-dir/unpacked/ginger-0.10.5.2-3c5c7e74779496d7de83bb400b7136656af67e5ccce8547b49055424c541c136/cli/
GingerCLI.hs:91:34: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at cli/GingerCLI.hs:7:8-11
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘Text.show’,
                     imported from ‘Data.Text’ at cli/GingerCLI.hs:11:1-24.
          |
       91 |         | otherwise = putStrLn . show $ value
          |                                  ^^^^
```

**Comment by TravisCardwell** [comment]
Thank you @juhp !

This was caused by an `import Data.Text as Text` (without `qualified`) that is likely unintentional.  The fix is included in [0.10.6.0](https://hackage.haskell.org/package/ginger-0.10.6.0) which I just released.
